import { CivilStatus, ColorRace, Formations } from './Auxiliaries';
import { Church } from './Church';
import { MemberOrigin } from './MemberOrigins';
import { Person } from './Person';

export type Members = {
  id: string;
  person_id: Person;
  church_id: Church;
  rg: string;
  issuing_body: string;
  civil_status_id: CivilStatus;
  nationality: string;
  naturalness: string;
  color_race_id: ColorRace;
  formation_id: Formations;
  formation_course: string;
  profission: string;
  def_physical: boolean;
  def_visual: boolean;
  def_hearing: boolean;
  def_intellectual: boolean;
  def_mental: boolean;
  def_multiple: boolean;
  def_other: boolean;
  def_other_description: string;
  baptism_date: string;
  baptism_locale: string;
  baptism_official: string;
  baptism_holy_spirit: boolean;
  baptism_holy_spirit_date: string;
  member_origin_id: MemberOrigin;
  receipt_date: string;
  created_at: string;
  updated_at: string;
};
