import "@/styles/global.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import ThemeProviderPage from "./theme-provider";

const poppins = Poppins({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by WILT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <ThemeProviderPage>{children}</ThemeProviderPage>
      </body>
    </html>
  );
}
