services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        user: "1000:1000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - db
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - laravel

    # db postgres
    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-holy}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-holy}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-holy} -d ${DB_DATABASE:-holy}" ]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - laravel

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@wilt.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-wilt}
            PGADMIN_LISTEN_PORT: 80
        networks:
            - laravel

    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
